name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/LICENSE'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/LICENSE'
      - '**/*.md'

env:
  DOCKER-CONTEXT: ./
  DOCKER-FILE: ./.github/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.DOCKER-CONTEXT }}
        file: ${{ env.DOCKER-FILE }}
        tags: ghcr.io/${{ github.repository_owner }}/mcl_unkown_obstacle_experiment:melodic
        build-args: USERNAME=runner
        no-cache: true
        push: false